// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUMg8lr6pm5tjCmUeR1g9dqomoi4rO0Ag',
    appId: '1:146733578533:web:eba3e7051a9caba7ca02cc',
    messagingSenderId: '146733578533',
    projectId: 'finwise-eed73',
    authDomain: 'finwise-eed73.firebaseapp.com',
    storageBucket: 'finwise-eed73.firebasestorage.app',
    measurementId: 'G-46BLYSY15Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmqsfqJDWs0MzjrEyKUDscQbFpldQL2Ac',
    appId: '1:146733578533:android:4c2417ac0c0e284bca02cc',
    messagingSenderId: '146733578533',
    projectId: 'finwise-eed73',
    storageBucket: 'finwise-eed73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyy5TCP6BRkZw3R6EbddSxL0NetEY20_s',
    appId: '1:146733578533:ios:f38edc08989373b8ca02cc',
    messagingSenderId: '146733578533',
    projectId: 'finwise-eed73',
    storageBucket: 'finwise-eed73.firebasestorage.app',
    iosBundleId: 'com.example.finWise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyy5TCP6BRkZw3R6EbddSxL0NetEY20_s',
    appId: '1:146733578533:ios:f38edc08989373b8ca02cc',
    messagingSenderId: '146733578533',
    projectId: 'finwise-eed73',
    storageBucket: 'finwise-eed73.firebasestorage.app',
    iosBundleId: 'com.example.finWise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUMg8lr6pm5tjCmUeR1g9dqomoi4rO0Ag',
    appId: '1:146733578533:web:37d99a4866889fe5ca02cc',
    messagingSenderId: '146733578533',
    projectId: 'finwise-eed73',
    authDomain: 'finwise-eed73.firebaseapp.com',
    storageBucket: 'finwise-eed73.firebasestorage.app',
    measurementId: 'G-ZYNBNG72WV',
  );
}
